# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  staydrysystems.com:
    site_hosts:
      - canonical: staging.staydrysystems.com
        # redirects:
        #   - www.staydrysystems.com
        #   - staydrysystems.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:cimocimocimo/staydrysystems.com.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: new-site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
    backup:
      enabled: true
      auto: true
      target: s3://s3.us-west-2.amazonaws.com/backup.staydrysystems.com # any location supported by duplicity
      schedule: '0 4 * * *' # cron time of backups (change this value)
      purge: true # switch to true to enable automatic purging of old backups
